
# PluginLG Role example

# Author Ph1Lou

# Link : https://www.spigotmc.org/resources/loup-garou-uhc.73113/

# Version 1.5 Snapshot

# You are not allowed to claim this plugin as your own.

# Copyright : All Rights Reserved - 2019
# Available (fr)

lang: fr



